"""The corpus is invented, and this is where that stops being a promise.

Every check here runs against the committed fixtures, so a document that came from somewhere
else — or a generator change that started producing valid identifiers — fails the suite rather
than being noticed by a reader.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from claims_rag.documents import load_documents

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"

CPF = re.compile(r"\b(\d{3})\.(\d{3})\.(\d{3})-(\d{2})\b")
CNPJ = re.compile(r"\b\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}\b")
#: A Brazilian court case number. None belongs in an insurance corpus; this catches a fixture
#: copied in from one of the other repositories by accident.
CNJ = re.compile(r"\b\d{7}-\d{2}\.\d{4}\.\d\.\d{2}\.\d{4}\b")


def corpus_text() -> str:
    return "\n".join(
        doc.text
        for name in ("documents.json", "truth.json")
        for doc in load_documents(FIXTURES / name)
    )


def cpf_check_digits(nine: str) -> tuple[int, int]:
    """The two digits a valid CPF would carry, by the official weighting."""

    def digit(seq: str) -> int:
        weight = len(seq) + 1
        total = sum(int(d) * (weight - i) for i, d in enumerate(seq))
        remainder = total % 11
        return 0 if remainder < 2 else 11 - remainder

    first = digit(nine)
    return first, digit(nine + str(first))


class TestNothingRealIsCommitted:
    def test_every_cpf_fails_its_check_digits(self) -> None:
        """The guarantee, computed rather than trusted.

        A CPF-shaped string with correct check digits is a number that can belong to a real
        person. Each of these is generated by computing the right digits and then writing
        different ones, so the shape is right and no validator will ever accept it.
        """
        found = CPF.findall(corpus_text())
        assert found, (
            "the corpus should contain CPF-shaped strings, so that this check means something"
        )
        for a, b, c, given in found:
            expected = "".join(str(d) for d in cpf_check_digits(a + b + c))
            assert given != expected, f"{a}.{b}.{c}-{given} has valid check digits"

    def test_no_cnpj_and_no_court_case_number(self) -> None:
        text = corpus_text()
        assert not CNPJ.search(text)
        assert not CNJ.search(text)

    def test_the_state_does_not_exist(self) -> None:
        # Every Brazilian state, so a real one appearing would be a document from elsewhere.
        real = [
            "Acre",
            "Alagoas",
            "Amapá",
            "Amazonas",
            "Bahia",
            "Ceará",
            "Espírito Santo",
            "Goiás",
            "Maranhão",
            "Mato Grosso",
            "Minas Gerais",
            "Pará",
            "Paraíba",
            "Paraná",
            "Pernambuco",
            "Piauí",
            "Rio de Janeiro",
            "Rio Grande do Norte",
            "Rio Grande do Sul",
            "Rondônia",
            "Roraima",
            "Santa Catarina",
            "São Paulo",
            "Sergipe",
            "Tocantins",
        ]
        text = corpus_text()
        assert "Zetalândia" in text
        for state in real:
            assert state not in text, f"a real state appears in the corpus: {state}"


class TestTheCorpusIsUsable:
    def test_the_documents_and_the_truth_cover_the_same_pages(self) -> None:
        read = {d.id: d for d in load_documents(FIXTURES / "documents.json")}
        truth = {d.id: d for d in load_documents(FIXTURES / "truth.json")}
        assert set(read) == set(truth)
        assert len(read) == 40

    def test_every_chunk_points_at_a_document_that_exists(self) -> None:
        read = {d.id for d in load_documents(FIXTURES / "documents.json")}
        payload = json.loads((FIXTURES / "chunks.json").read_text(encoding="utf-8"))
        chunks = payload["chunks"]
        assert chunks
        for row in chunks:
            assert row["document_id"] in read, row["id"]

    def test_the_ocr_actually_degraded_something(self) -> None:
        """If the error rate were zero the corpus would be a font rendering, not a scan.

        It would also make every downstream number meaningless: a retrieval system measured on
        perfectly clean text says nothing about one reading real documents.
        """
        measurements = json.loads((FIXTURES / "ocr-measurements.json").read_text(encoding="utf-8"))
        rates = [page["cer"] for page in measurements["pages"]]
        assert rates
        assert sum(rates) / len(rates) > 0.01, (
            "the OCR made essentially no mistakes; check the renderer"
        )
        assert sum(rates) / len(rates) < 0.40, "the OCR failed; the corpus is unusable"

    def test_folding_accents_removes_a_real_share_of_the_error(self) -> None:
        # The measurement behind the tokeniser's accent folding.
        measurements = json.loads((FIXTURES / "ocr-measurements.json").read_text(encoding="utf-8"))
        pages = measurements["pages"]
        raw = sum(p["cer"] for p in pages) / len(pages)
        folded = sum(p["cer_accent_folded"] for p in pages) / len(pages)
        assert folded < raw


class TestTheGoldenSetSaysItsOwnSize:
    """The structure that made a p-value meaningless, pinned so it cannot be forgotten again.

    The golden set is 64 rows and 8 distinct questions, each asked of every claim. That is eight
    clusters of eight, not 64 independent trials, and a sign test over rows counts one question
    failing everywhere as eight separate failures. This repository published `p = 0.013` on that
    basis for a week; at the question level the same comparison is a 2-2 tie.

    These assertions exist so that the next person to read the ablation — or the next version of
    me — cannot miss the shape of the design. If a future golden set adds distinct questions,
    these numbers change and the README's power discussion changes with them, in the same commit.
    """

    def test_the_rows_are_eight_questions_not_sixty_four(self) -> None:
        from claims_rag.pipeline import build

        corpus = build("fixtures")
        questions = {q.text for q in corpus.queries}
        assert len(corpus.queries) == 64
        assert len(questions) == 8, (
            f"{len(questions)} distinct questions behind {len(corpus.queries)} rows. The "
            "ablation's unit of analysis is the question; update compare_by_question's "
            "docstring and the README's power discussion together with this number."
        )

    def test_every_question_is_asked_of_every_claim(self) -> None:
        from collections import Counter

        from claims_rag.pipeline import build

        corpus = build("fixtures")
        per_question = Counter(q.text for q in corpus.queries)
        assert set(per_question.values()) == {8}, (
            "the questions are no longer balanced across claims, which breaks the assumption "
            "that averaging within a question is a fair cluster summary"
        )

    def test_the_clustered_test_is_what_the_report_leads_with(self) -> None:
        """The clustered comparison must exist and must disagree with the naive one here.

        If these ever agree on this corpus, either the golden set grew or something regressed in
        the clustering — both are things the next reader needs to know about.
        """
        from claims_rag.cli import CONFIGURATIONS, run_configuration
        from claims_rag.metrics import compare, compare_by_question, evaluate
        from claims_rag.pipeline import build

        corpus = build("fixtures")
        question_of = {q.id: q.text for q in corpus.queries}
        reports = {
            c.name: evaluate(
                corpus.queries,
                run_configuration(corpus, c, scoped=True),
                configuration=c.name,
                k=5,
            )
            for c in CONFIGURATIONS
            if c.name in {"dense-only", "hybrid-rrf"}
        }
        naive = compare(reports["dense-only"], reports["hybrid-rrf"])
        clustered = compare_by_question(reports["dense-only"], reports["hybrid-rrf"], question_of)
        assert naive.p_value < 0.05, "the naive test no longer finds the spurious effect"
        assert clustered.p_value > 0.05, (
            "the clustered test now finds the effect the naive one did. On 8 questions that "
            "would be surprising; check the golden set grew before believing it."
        )
